version: '3.9'

services: 
  salt-master:
    hostname: master
    build:
      context: .
      dockerfile: Master/dockerfile
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./salt/master.d:/etc/salt/master.d
      - ./srv:/srv
      - ./tls:/etc/salt/certs/tls
    ports:
      - "8000:8000"
    networks:
      - salt  
  salt-minion:
    build:
      context: .
      dockerfile: Minions/dockerfile
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    depends_on:
      - salt-master
    networks:
      - salt
networks:
  salt:
    name: playgroud
